concurrent = 4
check_interval = 0
shutdown_timeout = 0
log_level = "info"

[session_server]
  session_timeout = 1800

[[runners]]
  name = "docker-runner"
  url = "http://gitlab/"
  id = 1
  token = "jfz8getaL4F5CTnjJfrv"
  executor = "shell"
  shell = "bash"

